site_name: GCES OWASP 2023-1
theme:
  name: material
nav:
  - Home: index.md
  - Andé Alves:
    - Sprint 1: andre/sprint1.md
    - Sprint 2: andre/sprint2.md
    - Sprint 3: andre/sprint3.md
    - Sprint 4: andre/sprint4.md
    - Sprint 5: andre/sprint5.md
    - Sprint 6: andre/sprint6.md
  - Guilherme Rogelin Vial:
    - Sprint 1: guilherme/sprint1.md
    - Sprint 2: guilherme/sprint2.md
    - Sprint 3: guilherme/sprint3.md
    - Sprint 4: guilherme/sprint4.md
    - Sprint 5: guilherme/sprint5.md
    - Sprint 6: guilherme/sprint6.md
